class_name SelfUpdater
extends RefCounted
## The Windows self-replace-and-relaunch mechanism (update system).
##
## A running .exe can't overwrite itself on Windows, so the sequence is:
##   1. The game downloads the update zip and extracts the new .exe next to the
##      current one (same folder => a same-drive move, which is atomic).
##   2. The game writes a tiny .bat helper and launches it detached, then quits.
##   3. The helper waits until the old .exe is unlocked (the game has exited),
##      swaps the new build in, relaunches it, and deletes itself.
##
## The fiddly platform bits live here so the Updater stays about *policy*. The
## helper-script text is generated by a pure function so it can be unit-tested.
##
## NOTE: this can only be exercised end to end from a packaged build with a real
## release attached — in the editor self-update is refused (see Updater).

const HELPER_NAME := "gpbj_update.bat"


## Generates the helper batch script that performs the swap after the game exits.
## Pure (no side effects) so it's testable. Uses a ping-based wait loop because
## `timeout` needs a console the detached process won't have.
static func build_helper_bat(old_exe: String, new_exe: String) -> String:
	# %OLD%/%NEW% are quoted at use-sites; paths use backslashes for cmd.exe.
	var old_win := old_exe.replace("/", "\\")
	var new_win := new_exe.replace("/", "\\")
	return "\r\n".join([
		"@echo off",
		"setlocal",
		"set \"OLD=%s\"" % old_win,
		"set \"NEW=%s\"" % new_win,
		":waitloop",
		"del \"%OLD%\" >nul 2>&1",
		"if exist \"%OLD%\" (",
		"  ping -n 2 127.0.0.1 >nul",
		"  goto waitloop",
		")",
		"move /y \"%NEW%\" \"%OLD%\" >nul",
		"start \"\" \"%OLD%\"",
		"del \"%~f0\"",
		"",
	])


## Extracts the first .exe found in the zip into dest_dir. Returns the written
## path, or "" on any failure. Uses Godot's ZIPReader (no external tools).
static func extract_exe(zip_path: String, dest_dir: String) -> String:
	var reader := ZIPReader.new()
	if reader.open(zip_path) != OK:
		return ""
	var written := ""
	for entry in reader.get_files():
		if entry.to_lower().ends_with(".exe"):
			var bytes := reader.read_file(entry)
			# Name it distinctly so it never collides with the running exe.
			var out_path := dest_dir.path_join(entry.get_file() + ".new")
			var out := FileAccess.open(out_path, FileAccess.WRITE)
			if out == null:
				break
			out.store_buffer(bytes)
			out.close()
			written = out_path
			break
	reader.close()
	return written


## Writes the helper next to the game and launches it detached. Returns whether
## the helper process started. The caller must quit immediately after.
static func begin_swap(new_exe: String) -> bool:
	var old_exe := OS.get_executable_path()
	var helper_path := old_exe.get_base_dir().path_join(HELPER_NAME)
	var helper := FileAccess.open(helper_path, FileAccess.WRITE)
	if helper == null:
		return false
	helper.store_string(build_helper_bat(old_exe, new_exe))
	helper.close()
	# Detached so it survives this process quitting. cmd /c runs then exits.
	var pid := OS.create_process("cmd.exe", ["/c", helper_path.replace("/", "\\")])
	return pid != -1
